[package]
name = "rock-paper-scissors"
version = "0.1.0"
edition = "2021"

[dependencies.bevy]
version = "0.6.1"
default_features = false
features = [
		 "render",
		 "bevy_winit",
		 "png",
		 "x11",
		 "dynamic"
]
